language: julia
os:
    - linux
    - osx
julia:
    - 0.3
    - 0.4
    - nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone("https://github.com/gragusa/Divergences.jl.git")'
				- julia -e 'Pkg.clone("https://github.com/gragusa/ModelsGenerators.git")'
- julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("MomentBasedEstimators"); Pkg.test("MomentBasedEstimators"; coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("MomentBasedEstimators")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'